### ISSUE TITLE
android平台无法正常工作

### ISSUE THREAD

**Issue by Symous** [gizwits/cordova-gizwits-scan-qrcode#1]
老哥，ios好用，但是android无法正常工作，Android Studio无法正常加载module：gizscanqrcode导致编译不通过。

**Comment by kylewang4929** [comment]
能把详细的内容贴一下吗

**Comment by kylewang4929** [comment]
我们已经更新了一版，可以再试一下吗。github没有经常在维护，但是npm的版本是最新的，你可以用那个

**Comment by Symous** [comment]
@kylewang4929 好的，老哥，时间太久了。。。之前的无法加载module的问题我已经通过一些方法让他可以运行了，新版本我抽空试一下，谢谢。
